<?php
// auto-generated by sfPropelCrud
// date: 2006/09/24 16:12:14
?>
<?php use_helper('Object') ?>

<?php echo form_tag('codiciiva/update') ?>

<?php echo object_input_hidden_tag($codice_iva, 'getId') ?>

<h2><?php if($codice_iva->isNew()):?>Nuovo Codice<?php else:?>Modifica Codice<?php endif?></h2>

<?php if ($sf_request->hasErrors()): ?>
<div class="validate-error">
  <p>I dati inseriti non sono corretti.
  Correggi i seguenti errori e salva i dati di nuovo:</p>
</div>
<?php endif ?>

<fieldset>
<legend>Codice</legend>

<table class="fattura">
<tbody>
<tr>
  <th>Nome:</th>
  <td><?php echo object_input_tag($codice_iva, 'getNome', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('nome')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('nome')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Valore:</th>
  <td><?php echo object_input_tag($codice_iva, 'getValore', array (
  'size' => 7,
)) ?></td>
<?php if($sf_request->hasError('valore')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('valore')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Descrizione:</th>
  <td><?php echo object_textarea_tag($codice_iva, 'getDescrizione', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
<td colspan="2" colspan="2"><?php echo submit_tag('Salva') ?></td>
</tr>
</tbody>
</table>
</fieldset>
</form>
