<?php
// auto-generated by sfPropelCrud
// date: 2006/09/21 23:32:23
?>
<?php

/**
 * bug actions.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage bug
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 1415 2006-06-11 08:33:51Z fabien $
 */
class bugActions extends sfActions
{
  public function executeIndex ()
  {
    return $this->forward('bug', 'create');
  }

  public function executeList ()
  {
    $this->bugs = BugPeer::doSelect(new Criteria());
  }

  public function executeShow ()
  {
    $this->bug = BugPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->bug);
  }

  public function executeCreate ()
  {
    $this->bug = new Bug();

    $this->setTemplate('edit');
  }


  public function executeUpdate ()
  {
    
    $bug = new Bug();
    $bug->setId($this->getRequestParameter('id'));
    $bug->setIdUtente($this->getUser()->getAttribute('id_utente'));
    $bug->setPriorita($this->getRequestParameter('priorita'));
    $bug->setModulo($this->getRequestParameter('modulo'));
    $bug->setTesto($this->getRequestParameter('testo'));
    $bug->setStato('in fase di approvazione');
    $bug->setData(date('y-m-d',time()));

    $bug->save();

    return $this->redirect('bug/show?id='.$bug->getId());
  }
  
  public function handleErrorUpdate(){
  	$this->forward('bug','create');
  }

}
