<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:05:45
?>
<?php

/**
 * banca actions.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage banca
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 1415 2006-06-11 08:33:51Z fabien $
 */
class bancaActions extends sfActions
{
  public function executeIndex ()
  {
    return $this->forward('banca', 'list');
  }

  public function executeList ()
  {
    $this->bancas = BancaPeer::doSelect(new Criteria());
  }

  /*public function executeShow ()
  {
    $this->banca = BancaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->banca);
  }*/

  public function executeCreate ()
  {
    $this->banca = new Banca();

    $this->setTemplate('edit');
  }

  public function executeEdit ()
  {
    $this->banca = BancaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->banca);
  }

  public function executeUpdate ()
  {
    if (!$this->getRequestParameter('id', 0))
    {
      $banca = new Banca();
    }
    else
    {
      $banca = BancaPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($banca);
    }

    $banca->setId($this->getRequestParameter('id'));
    $banca->setIdUtente($this->getUser()->getAttribute('id_utente'));
    $banca->setAbi($this->getRequestParameter('abi'));
    $banca->setCab($this->getRequestParameter('cab'));
    $banca->setCin($this->getRequestParameter('cin'));
    $banca->setNumeroConto($this->getRequestParameter('numero_conto'));
    $banca->setNomeBanca($this->getRequestParameter('nome_banca'));
    $banca->setIban($this->getRequestParameter('iban'));
    
    $banca->save();

    return $this->redirect('banca/list');
  }

  public function executeDelete ()
  {
    $banca = BancaPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($banca);

    $banca->delete();

    return $this->redirect('banca/list');
  }
  
  public function handleErrorUpdate()
  {
  	if(!$this->getRequestParameter('id',0))
  		$this->forward('banca','create');
  	else
    	$this->forward('banca','edit');
  }
}
