<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:05:45
?>
<?php use_helper('Object') ?>

<?php echo form_tag('banca/update') ?>

<?php echo object_input_hidden_tag($banca, 'getId') ?>

<h2><?php if($banca->isNew()):?>Nuova Banca<?php else:?>Modifica Banca<?php endif?></h2>


<?php if ($sf_request->hasErrors()): ?>
<div class="validate-error">
  <p>I dati inseriti non sono corretti.
  Correggi i seguenti errori e salva i dati di nuovo:</p>
</div>
<?php endif ?>

<fieldset>
<legend>Coordinate Bancarie</legend>

<table class="banca">
<tbody>
<tr>
  <th>Nome banca*:</th>
  <td><?php echo object_input_tag($banca, 'getNomeBanca', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('nome_banca')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('nome_banca')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Abi*:</th>
  <td><?php echo object_input_tag($banca, 'getAbi', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('abi')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('abi')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Cab*:</th>
  <td><?php echo object_input_tag($banca, 'getCab', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('cab')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('cab')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Cin*:</th>
  <td><?php echo object_input_tag($banca, 'getCin', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('cin')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('cin')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Numero conto*:</th>
  <td><?php echo object_input_tag($banca, 'getNumeroConto', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('numero_conto')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('numero_conto')?>
</td>
<?php endif?>
</tr>

<tr>
  <th>Iban:</th>
    <td><?php echo object_input_tag($banca, 'getIban', array (
      'size' => 20,
      )) ?></td>
      <?php if($sf_request->hasError('iban')):?>
      <td class="validate-error">
      <?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('iban')?>
      </td>
      <?php endif?>
      </tr>

<tr><td colspan="2" align="right"><?php echo link_to('Annulla', 'banca/list') ?>&nbsp;<?php echo submit_tag('Salva') ?></td></tr>
</tbody>
</table>
</fieldset>

</form>
