<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:05:45
?>
<h2>Banche</h2>

<?php if(count($bancas) > 0):?>
<table class="fatture">
<thead>
<tr>
  <th>Nome</th> 
  <th>Abi</th>
  <th>Cab</th>
  <th>Cin</th>
  <th>Numero conto</th>
  <th>Iban</th>
 <th></th>
</tr>
</thead>
<tbody>
<?php foreach ($bancas as $banca): ?>
<tr>
	  <td><?php echo link_to($banca->getNomeBanca(), 'banca/edit?id='.$banca->getId(),array('title'=>'Modifica Coordinate Bancarie')) ?></td>
      <td><?php echo $banca->getAbi() ?></td>
      <td><?php echo $banca->getCab() ?></td>
      <td><?php echo $banca->getCin() ?></td>
      <td><?php echo $banca->getNumeroConto() ?></td>
      <td><?php echo $banca->getIban() ?></td>
      <td><?php echo link_to(image_tag('icons_tango/trash-full.png'), 'banca/delete?id='.$banca->getId(), 'post=true&confirm=vuoi cancellare queste coordinate bancarie?') ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php else:?>
<p>Nessuna banca disponibile, <?php echo link_to('inserisci le tue coordinate bancarie','banca/create')?>.</p>
<?php endif?>
