<?php
// auto-generated by sfPropelCrud
// date: 2006/08/29 09:50:52
?>
<?php use_helper('Object') ?>

<?php echo form_tag('prodotto/update') ?>

<?php echo object_input_hidden_tag($prodotto, 'getId') ?>

<h2><?php if($prodotto->isNew()):?>Nuovo Prodotto<?php else:?>Modifica Prodotto<?php endif?></h2>

<?php if ($sf_request->hasErrors()): ?>
<div class="validate-error">
  <p>I dati inseriti non sono corretti.
  Correggi i seguenti errori e salva i dati di nuovo:</p>
</div>
<?php endif ?>

<fieldset>
<legend>Dati Prodotto</legend>

<table class="banca">
<tbody>
<tr>
  <th>Codice Prodotto:</th>
  <td><?php echo object_input_tag($prodotto, 'getCodice', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('codice')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('codice')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Nome*:</th>
  <td><?php echo object_input_tag($prodotto, 'getNome', array (
  'size' => 40,
)) ?></td>
<?php if($sf_request->hasError('nome')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('nome')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Prezzo*:</th>
  <td><?php echo object_input_tag($prodotto, 'getPrezzo', array (
  'size' => 7,
)) ?> &euro;</td>
<?php if($sf_request->hasError('prezzo')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('prezzo')?>
</td>
<?php endif?>
</tr>
<tr><td colspan="2" align="right"><?php echo link_to('Annulla', 'prodotto/list') ?>&nbsp;<?php echo submit_tag('Salva') ?></td></tr>
</tbody>
</table>

</fieldset>

</form>
