<?php
// auto-generated by sfPropelCrud
// date: 12/26/2005 22:00:03
?>
<h1>dettagliFattura</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Fattura id</th>
  <th>Descrizione</th>
  <th>Qty</th>
  <th>Sconto</th>
  <th>Prezzo</th>
</tr>
</thead>
<tbody>
<?php foreach ($dettagli_fatturas as $dettagli_fattura): ?>
<tr>
    <td><?php echo link_to($dettagli_fattura->getId(), 'dettagliFattura/show?id='.$dettagli_fattura->getId()) ?></td>
      <td><?php echo $dettagli_fattura->getFatturaId() ?></td>
      <td><?php echo $dettagli_fattura->getDescrizione() ?></td>
      <td><?php echo $dettagli_fattura->getQty() ?></td>
      <td><?php echo $dettagli_fattura->getSconto() ?></td>
      <td><?php echo $dettagli_fattura->getPrezzo() ?></td>
  </tr>
<?php endforeach ?>
</tbody>
</table>

<?php echo link_to ('create', 'dettagliFattura/edit') ?>
