<?php
// auto-generated by sfPropelCrud
// date: 2006/08/15 03:52:09
?>


<?php use_helper('Object') ?>

<?php if($utente->isNew()):?>
<?php echo form_tag('utente/register') ?>
<?php else:?>
<?php echo form_tag('utente/update') ?>
<?php endif?>

<?php echo object_input_hidden_tag($utente, 'getId') ?>

<div class="title">
  <h2><?php echo $utente->isNew()?'Registrazione Nuovo Utente':'Modifica il tuo profilo'?>
</div>


<?php if($sf_request->hasAttribute('success')):?>
<span style="color:red;font-size: 70%;">- <?php echo $sf_request->getAttribute('success')?></span>
<?php endif?>
</h2>

<?php if($utente->isNew()):?>
<p style="color: #BF0000"><strong><?php echo link_to('Per registrarsi &egrave; necessario richiedere il codice d\'invito','utente/askcode','style="color: #BF0000"')?></strong>.</p>
<?php endif?>

<?php if ($sf_request->hasErrors()): ?>
<div class="validate-error">
  <p>I dati inseriti non sono corretti.
  Correggi i seguenti errori e salva i dati di nuovo:</p>
</div>
<?php endif ?>

<table class="edit" width="100%">
<?php if($utente->isNew()):?>

<tr>
<th>Codice d'invito:&nbsp;&nbsp;</th>
<td><?php echo input_tag('id_codice',null,array('size'=>20))?></td>
<?php if($sf_request->hasError('id_codice')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('id_codice')?>
</td>
<?php endif?>
</tr>
<tr><td colspan="2">&nbsp;</tr>
<?php endif?>
<tr>
  <th>Username:</th>
<?php if($utente->isNew()):?>
  <td><?php echo object_input_tag($utente, 'getUsername', array (
  'size' => 20,
)) ?></td>
<?php else:?>
  <td><?php echo $utente->getUsername()?></td>
<?php endif?>
<?php if($sf_request->hasError('username')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('username')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Nome*:</th>
  <td><?php echo object_input_tag($utente, 'getNome', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('nome')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('nome')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Cognome*:</th>
  <td><?php echo object_input_tag($utente, 'getCognome', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('cognome')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('cognome')?>
</td>
<?php endif?>
</tr>
<?php if(!$utente->isNew()):?>
<tr>
  <th>Ragione sociale:</th>
  <td><?php echo object_input_tag($utente, 'getRagioneSociale', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('ragione_sociale')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('ragione_sociale')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Partita iva:</th>
  <td><?php echo object_input_tag($utente, 'getPartitaIva', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('partita_iva')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('partita_iva')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Codice fiscale:</th>
  <td><?php echo object_input_tag($utente, 'getCodiceFiscale', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('codice_fiscale')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('codice_fiscale')?>
</td>
<?php endif?>
</tr>
<?php endif?>
<tr>
  <th>Email*:</th>
  <td><?php echo object_input_tag($utente, 'getEmail', array (
  'size' => 20,
)) ?></td>
<?php if($sf_request->hasError('email')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('email')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Password*:</th>
  <td><?php echo input_password_tag() ?></td>
  <?php if($sf_request->hasError('password')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('password')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Verifica Password*:</th>
  <td><?php echo input_password_tag('verifica_password') ?></td>
  <?php if($sf_request->hasError('verifica_password')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('verifica_password')?>
</td>
<?php endif?>
</tr>
<?php if($utente->isNew()):?>
<tr><td colspan="2">&nbsp;</td></tr>
<tr>
<th valign="top">Codice Sicurezza:</th>
<td>
<img src="<?php echo url_for('utente/antispam'); ?>" /><br/><br/>
<?php echo input_tag('captcha',null,array('size'=>12)) ?>
</td>
<?php if($sf_request->hasError('captcha')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('captcha')?>
</td>
<?php endif?>
</tr>
<tr>
<td colspan="2">&nbsp;</td></tr>
<tr>
<th valign="top">Condizioni d'uso:</th>
<td>
<p><small>Inviandoci questo form di registrazione, dai contemporanemente la tua accettazione delle nostre Condizioni d'Uso.<br/> Puoi leggerle nel dettaglio qui.</small></p>
<textarea style="font-size: 11px" cols="60" rows="10"><?php include_partial('utente/contratto');?></textarea>
<div style="margin-top: 5px;text-align: center;">
<?php echo radiobutton_tag('contratto',1,$sf_request->getParameter('contratto')==1?true:false);?> <small>Approvo</small>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<?php echo radiobutton_tag('contratto',null,$sf_request->getParameter('contratto')==0?true:false);?> <small>Non Approvo</small>
</div>
</td>
<?php if($sf_request->hasError('contratto')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('contratto')?>
</td>
<?php endif?>
</tr>
<tr>
<tr>
<th valign="top">Privacy:</th>
<td>
<textarea cols="60" rows="10" style="font-size: 11px"><?php include_partial('utente/privacy');?></textarea>
<p><small>CONSENSO EX ART. 23 DEL D.LGS. N.196/03<br/>
Letta l'informativa:</small> </p>
<div style="margin-top: 5px;text-align: center;">
<?php echo radiobutton_tag('privacy',1,$sf_request->getParameter('contratto')==1?true:false);?> <small>Approvo</small>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<?php echo radiobutton_tag('privacy',null,$sf_request->getParameter('contratto')==0?true:false);?> <small>Non Approvo</small>
</td>
<?php if($sf_request->hasError('privacy')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('privacy')?>
</td>
<?php endif?>
</tr>
<?php endif?>
<tr>
<td colspan="2" align="center"><?php echo submit_tag(($utente->isNew()?'Registrati':'Salva Profilo'))?>&nbsp;<?php echo $utente->isNew()?link_to('Annulla','utente/show'):''?></td>
</tr>
</table>
</form>
