<?php
// auto-generated by sfPropelCrud
// date: 2006/08/15 03:52:09
?>

<?php echo object_input_hidden_tag($utente, 'getId') ?>

<div class="title">
  <h2><?php echo $utente->isNew()?'Registrazione Nuovo Utente':'Modifica il tuo profilo'?>
</div>

<?php if($sf_request->hasAttribute('success')):?>
<span style="color:red;font-size: 70%;">- <?php echo $sf_request->getAttribute('success')?></span>
<?php endif?>
</h2>

<?php if($utente->isNew()):?>
<p style="color: #BF0000"><strong><?php echo link_to('Per registrarsi &egrave; necessario richiedere il codice d\'invito','utente/askcode','style="color: #BF0000"')?></strong>.</p>
<?php endif?>

<?php if($utente->isNew()):?>
  <form action="<?php echo url_for('utente/register')?>" method="post">
<?php else:?>
  <form action="<?php echo url_for('utente/update')?>" method="post">
<?php endif?>
  <table class="edit" width="100%">
    <?php echo $form; ?>
    <tr>
      <td colspan="2" align="right"><?php echo submit_tag('Salva')?></td>
    </tr>
  </table>
</form>

