<?php
// auto-generated by sfPropelCrud
// date: 2006/09/21 23:32:23
?>
<h2>I miei Bug</h2>
<p><?php echo link_to('Inserisci un nuovo bug','bug/create')?></p>

<table class="fatture" style="margin-top: 10px;">
<thead>
<tr>
  <th>ID</th>
  <th>Priorita</th>
  <th>Modulo</th>
  <th>Data Inserimento</th>
  <th>Stato</th>
</tr>
</thead>
<tbody>
<?php foreach ($bugs as $index => $bug): ?>
<tr>
	  <td><?php echo link_to($index+1,'bug/show?id='.$bug->getId())?></td>
      <td><?php echo ucfirst($bug->getPriorita()) ?></td>
      <td><?php echo ucfirst($bug->getModulo()) ?></td>
      <td><?php echo $bug->getData() ?></td>
      <td><?php echo ucfirst($bug->getStato()) ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>