<?php
// auto-generated by sfPropelCrud
// date: 2006/09/21 23:32:23
?>

<h2>Bug</h2>
<p><?php echo link_to('Visualizza i miei bug','bug/list')?></p>

<table class="fatture" style="margin-top: 10px;">
<tbody>
<tr>
<th>Priorita: </th>
<td><?php echo $bug->getPriorita() ?></td>
</tr>
<tr>
<th>Modulo: </th>
<td><?php echo $bug->getModulo() ?></td>
</tr>
<tr>
<th>Testo: </th>
<td><?php echo $bug->getTesto() ?></td>
</tr>
<tr>
<th>Data Inserimento: </th>
<td><?php echo $bug->getData() ?></td>
</tr>
</tbody>
</table>