<?php
// auto-generated by sfPropelCrud
// date: 2006/08/29 09:50:52
?>
<h2>Prodotti</h2>

<?php if(count($prodottos) > 0):?>
<table class="fatture">
<thead>
<tr>
  <th>Codice</th>
  <th>Nome</th>
  <th>Prezzo</th>
  <th></th>
</tr>
</thead>
<tbody>
<?php foreach ($prodottos as $prodotto): ?>
<tr>
	<td><?php echo $prodotto->getCodice() ?></td>
    <td style="text-align: left"><?php echo link_to($prodotto->getNome(), 'prodotto/edit?id='.$prodotto->getId()) ?></td>
    <td><?php echo $prodotto->getPrezzo() ?> &euro;</td>
    <td><?php echo link_to(image_tag('icons_tango/trash-full.png'), 'prodotto/delete?id='.$prodotto->getId(), 'post=true&confirm=vuoi cancellare questo prodotto?') ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php else:?>
<p>Nessun prodotto disponibile, <?php echo link_to('inserisci i prodotti che fatturi pi&ugrave; frequentemente','prodotto/create')?>.</p>
<?php endif?>
