<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:09:09
?>
<?php

/**
 * tassa actions.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage tassa
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 1415 2006-06-11 08:33:51Z fabien $
 */
class tassaActions extends sfActions
{
  public function executeIndex ()
  {
    return $this->forward('tassa', 'list');
  }

  public function executeList ()
  {
    $this->tassas = TassaPeer::doSelect(new Criteria());
  }

  /*public function executeShow ()
  {
    $this->tassa = TassaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->tassa);
  }*/

  public function executeCreate ()
  {
    $this->tassa = new Tassa();

    $this->setTemplate('edit');
  }

  public function executeEdit ()
  {
    $this->tassa = TassaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->tassa);
  }

  public function executeUpdate ()
  {
    if (!$this->getRequestParameter('id', 0))
    {
      $tassa = new Tassa();
    }
    else
    {
      $tassa = TassaPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($tassa);
    }

    $tassa->setId($this->getRequestParameter('id'));
    $tassa->setIdUtente($this->getUser()->getAttribute('id_utente'));
    $tassa->setNome($this->getRequestParameter('nome'));
    $tassa->setValore($this->getRequestParameter('valore'));
    $tassa->setDescrizione($this->getRequestParameter('descrizione'));

    $tassa->save();

    return $this->redirect('tassa/list');
  }

  public function executeDelete ()
  {
    $tassa = TassaPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($tassa);

    $tassa->delete();

    return $this->redirect('tassa/list');
  }
  
  public function handleErrorUpdate()
  {
  	if(!$this->getRequestParameter('id',0))
  		$this->forward('tassa','create');
  	else
    	$this->forward('tassa','edit');
  }
}
