<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:09:56
?>
<?php

/**
 * temafattura actions.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage temafattura
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 1415 2006-06-11 08:33:51Z fabien $
 */
class temafatturaActions extends sfActions
{
  public function executeIndex ()
  {
    return $this->forward('temafattura', 'list');
  }

  public function executeList ()
  {
    $this->tema_fatturas = TemaFatturaPeer::doSelect(new Criteria());
  }

  /*public function executeShow ()
  {
    $this->tema_fattura = TemaFatturaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->tema_fattura);
  }*/

  public function executeCreate ()
  {
    $this->tema_fattura = new TemaFattura();
	  $this->tema_fattura->setTemplate(file_get_contents(sfConfig::get('sf_data_dir').DIRECTORY_SEPARATOR.'template_fattura'.DIRECTORY_SEPARATOR.'template.htm'));
	  $this->tema_fattura->setCss(file_get_contents(sfConfig::get('sf_data_dir').DIRECTORY_SEPARATOR.'template_fattura'.DIRECTORY_SEPARATOR.'stile.css'));
    $this->setTemplate('edit');
  }

  public function executeEdit ()
  {
    $this->tema_fattura = TemaFatturaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->tema_fattura);
  }

  public function executeUpdate ()
  {
    if (!$this->getRequestParameter('id', 0))
    {
      $tema_fattura = new TemaFattura();
    }
    else
    {
      $tema_fattura = TemaFatturaPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($tema_fattura);
    }

    $tema_fattura->setId($this->getRequestParameter('id'));
    $tema_fattura->setIdUtente($this->getUser()->getAttribute('id_utente'));
    $tema_fattura->setNome($this->getRequestParameter('nome'));
    $tema_fattura->setTemplate($this->getRequestParameter('template'));
    $tema_fattura->setCss($this->getRequestParameter('css'));

    if(!$this->getRequest()->hasFileError('logo')){
    	$extension = $this->getRequest()->getFileExtension('logo');

    	$thumbnail = new sfThumbnail(150, 150);
  		$thumbnail->loadFile($this->getRequest()->getFilePath('logo'));
  		$thumbnail->save(sfConfig::get('sf_upload_dir').'/thumbnail/'.$this->getUser()->getAttribute('id_utente').'_logo.jpeg', 'image/png');


  		$this->getRequest()->moveFile('logo', sfConfig::get('sf_upload_dir').'/'.$this->getUser()->getAttribute('id_utente').'_logo.jpeg');
  		$tema_fattura->setLogo($this->getUser()->getAttribute('id_utente').'_logo.jpeg');
    }

  	$tema_fattura->save();

    $this->getRequest()->setAttribute('success','Tema salvato con successo');
    $this->getRequest()->setParameter('id',$tema_fattura->getId());
    return $this->redirect('temafattura/edit?id='.$tema_fattura->getId().'&success=1');
  }

  public function executeDelete ()
  {
    $tema_fattura = TemaFatturaPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($tema_fattura);

    $tema_fattura->delete();

    return $this->redirect('temafattura/list');
  }

  public function handleErrorUpdate()
  {
  	if(!$this->getRequestParameter('id',0))
  	$this->forward('temafattura','create');
  	else
  	$this->forward('temafattura','edit');
  }

  public function executeHelp(){

  }
}
