<?php include_partial('fattura/filter_success',array('anni_fatture'=>$anni_fatture,
													 'anno'=>$anno,
													 'cliente_id'=>$cliente_id,
													 'cliente'=>$cliente,
													 'stato'=>$stato,
													 'tipo' => $tipo,
													 'fatture'=>$fatture_pager,
													 'fatture_results'=>$fatture_pager->getResults(),
													 'form_action'=>'fattura/listFilter?cliente_id='.$cliente_id.'&',
													 'customer'=>false,
													 'checkbox'=>false,
													 'copia'=>false,
													 'div_to_update'=>'scheda_cliente',
													 'tags'=>$tags,
													 'tag_selected'=>$tag));?>
