<?php

// auto-generated by sfPropelCrud
// date: 2006/08/16 01:08:07
?>
<?php

/**
 * impostazione actions.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage impostazione
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 1415 2006-06-11 08:33:51Z fabien $
 */
class impostazioneActions extends sfActions
{

  private function update($request)
  {
    $this->form->bind($request->getParameter('impostazione', 0));
    if ($this->form->isValid()) 
    {
      $impostazione = $this->form->save();
      $impostazione->setRitenutaAcconto($request->getPostParameter('impostazione[ritenuta_acconto]').'/100');
      $impostazione->setIdUtente($this->getUser()->getAttribute('id_utente'));
      $impostazione->save();
      return $impostazione;
    }
    return false;
  }
  
  public function executeIndex()
  {
    return $this->forward('impostazione', 'edit');
  }

  public function executeCreate()
  {
    return $this->forward('impostazione', 'edit');
  }
  
  public function executeEdit($request)
  {
    $this->impostazione = ImpostazionePeer::retrieveByIdUtente($this->getUser()->getAttribute('id_utente'));
    
    if (!$this->impostazione)
    {
      $impostazione = new Impostazione();
    } 

    $ritenutaAcconto = explode('/', $this->impostazione->getRitenutaAcconto());
    
    $this->impostazione->setRitenutaAcconto($ritenutaAcconto[0]);
    
    $this->form = new ImpostazioneForm($this->impostazione);
    
    if($request->isMethod('post')) 
    {
      $impostazione = $this->update($request);
      if($impostazione) 
      {
        $this->getRequest()->setParameter('success', 'Impostazioni modificate con successo.');
        $this->getUser()->setAttribute('impostazioni', $impostazione);
      }
    }
  }
}
