<?php
// auto-generated by sfPropelCrud
// date: 2006/09/24 16:12:14
?>

<h2>Codici Iva</h2>

<?php if(count($codice_ivas) > 0):?>
<table class="fatture">
<thead>
<tr>
  <th>Nome</th>
  <th>Valore</th>
  <th>Descrizione</th>
  <th></th>
</tr>
</thead>
<tbody>
<?php foreach ($codice_ivas as $codice_iva): ?>
<tr>
    <td><?php echo link_to($codice_iva->getNome(), 'codiciiva/edit?id='.$codice_iva->getId()) ?></td>
      <td><?php echo $codice_iva->getValore() ?></td>
      <td><?php echo $codice_iva->getDescrizione() ?></td>
      <td><?php echo link_to(image_tag('icons_tango/trash-full.png'), 'codiciiva/delete?id='.$codice_iva->getId(), 'post=true&confirm=vuoi cancellare questo codice iva?') ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php else:?>
<p>Nessuna codice iva disponibile, <?php echo link_to('inserisci il tuo codice','codiciiva/create')?>.</p>
<?php endif?>
