<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:09:56
?>

<h2><?php if($tema_fattura->isNew()):?>Nuovo Tema<?php else:?>Modifica Tema<?php endif?>

<?php if($sf_request->hasParameter('success')):?>
<span style="color:red;font-size: 70%;">- Tema aggiornato con successo</span>
<?php endif?>
</h2>
<div id="edit-options">
<?php use_helper('Object') ?>

<?php echo form_tag('temafattura/update', 'multipart=true') ?>

<?php echo object_input_hidden_tag($tema_fattura, 'getId') ?>

<?php if ($sf_request->hasErrors()): ?>
<div class="validate-error">
  <p>I dati inseriri non sono corretti.
  Correggi i seguenti errori e salva i dati di nuovo:</p>
</div>
<?php endif ?>

<ul>
<li id="li-nome" class="selected">
<?php echo ($sf_request->hasError('nome')?image_tag('icons/icon_alert.gif',array('align'=>'top')).'&nbsp;':'')?>
<?php echo link_to_function('Nome Tema',
							visual_effect('fade','header',array('duration'=> 0))
							.visual_effect('fade','css',array('duration'=> 0))
							.visual_effect('appear','nome',array('duration'=> 0))
							."Element.addClassName('li-nome','selected');"
							."Element.removeClassName('li-header','selected');"
							."Element.removeClassName('li-css','selected');"
							)?></li>
							
							
<li id="li-header">
<?php echo ($sf_request->hasError('template')?image_tag('icons/icon_alert.gif',array('align'=>'top')).'&nbsp;':'')?>
<?php echo link_to_function('Modello Fattura',
							visual_effect('fade','nome',array('duration'=> 0))
							.visual_effect('fade','css',array('duration'=> 0))
							.visual_effect('appear','header',array('duration'=> 0))
							."Element.addClassName('li-header','selected');"
							."Element.removeClassName('li-nome','selected');"
							."Element.removeClassName('li-css','selected');"
							)?>
</li>
<li id="li-css">
<?php echo ($sf_request->hasError('css')?image_tag('icons/icon_alert.gif',array('align'=>'top')).'&nbsp;':'')?>
<?php echo link_to_function('Stile Fattura',
							visual_effect('fade','nome',array('duration'=> 0))
							.visual_effect('fade','header',array('duration'=> 0))
							.visual_effect('appear','css',array('duration'=> 0))
							."Element.addClassName('li-css','selected');"
							."Element.removeClassName('li-nome','selected');"
							."Element.removeClassName('li-header','selected');"
							)?>
</li>
</ul>

<div class="fieldset tema-fattura <?php echo $sf_request->hasErrors()?'tema-validate-error':''?>" id="nome">

<table class="banca">
<tr>
<th>Nome*:</th>
<td><?php echo object_input_tag($tema_fattura,'getNome')?>
</td>
<?php if($sf_request->hasError('nome')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('nome')?>
</td>
<?php endif?>
</tr>
<tr>
<th>Logo Ditta:</th>
<td>

<?php if($tema_fattura->getLogo()):?>
<table style="margin-bottom: 5px;margin-top: 5px;">
<tr>
<td>
<?php echo image_tag('/'.sfConfig::get('sf_upload_dir_name').'/thumbnail/'.$tema_fattura->getLogo()) ?>

</td>
</tr>
</table>
<?php endif?>

<?php echo input_file_tag('logo') ?>

</td>
<?php if($sf_request->hasError('logo')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('logo')?>
</td>
<?php endif?>
</tr>
<tr>
<td align="right" colspan="2"><?php echo submit_tag('Salva')?></td>
</tr>
</table>

</div>

<div class="fieldset tema-fattura <?php echo $sf_request->hasErrors()?'tema-validate-error':''?>" id="header" style="display: none;">

<table class="banca">
<tr>
  <th>Modello Fattura*:</th>
  <td><?php echo object_textarea_tag($tema_fattura, 'getTemplate',array('rich'=>false,'size'=>'80x27')
) ?></td>
<?php if($sf_request->hasError('template')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('template')?>
</td>
<?php endif?>
</tr>
<tr>
<td align="right" colspan="2"><?php echo submit_tag('Salva')?></td>
</tr>
</table>

</div>

<div class="fieldset tema-fattura <?php echo $sf_request->hasErrors()?'tema-validate-error':''?>" id="css" style="display: none;">

<table class="banca">
<tr>
  <th>Stile Fattura*:</th>
  <td><?php echo object_textarea_tag($tema_fattura, 'getCss', array (
  'size' => '80x27',
)) ?></td>
<?php if($sf_request->hasError('css')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('css')?>
</td>
<?php endif?>
</tr>
<tr>
<td align="right" colspan="2"><?php echo submit_tag('Salva')?></td>
</tr>
</table>

</div>

</form>

</div>