<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:09:56
?>
<h2>Temi Fattura</h2>

<?php if(count($tema_fatturas) > 0):?>
<table class="fatture">
<thead>
<tr>
  <th>Nome</th>
  <th></th>
</tr>
</thead>
<tbody>
<?php foreach ($tema_fatturas as $tema_fattura): ?>
<tr>
    <td><?php echo link_to($tema_fattura->getNome(), 'temafattura/edit?id='.$tema_fattura->getId()) ?></td>
    <td><?php echo link_to(image_tag('icons_tango/trash-full.png'), 'temafattura/delete?id='.$tema_fattura->getId(), 'post=true&confirm=Vuoi eliminiare questo tema?') ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php else:?>
<p>Nessun tema disponibile, <?php echo link_to('crea il tuo tema fattura','temafattura/create')?>.</p>
<?php endif?>