<?php
// auto-generated by sfPropelCrud
// date: 2006/09/24 16:12:02
?>
<?php

/**
 * modipagamento actions.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage modipagamento
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 1415 2006-06-11 08:33:51Z fabien $
 */
class modipagamentoActions extends sfActions
{
  public function executeIndex ()
  {
    return $this->forward('modipagamento', 'list');
  }

  public function executeList ()
  {
    $this->modo_pagamentos = ModoPagamentoPeer::doSelect(new Criteria());
  }

  public function executeCreate ()
  {
    $this->modo_pagamento = new ModoPagamento();

    $this->setTemplate('edit');
  }

  public function executeEdit ()
  {
    $this->modo_pagamento = ModoPagamentoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->modo_pagamento);
  }

  public function executeUpdate ()
  {
    if (!$this->getRequestParameter('id', 0))
    {
      $modo_pagamento = new ModoPagamento();
    }
    else
    {
      $modo_pagamento = ModoPagamentoPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($modo_pagamento);
    }

    $modo_pagamento->setId($this->getRequestParameter('id'));
    $modo_pagamento->setIdUtente($this->getUser()->getAttribute('id_utente'));
    $modo_pagamento->setNumGiorni($this->getRequestParameter('num_giorni'));
    $modo_pagamento->setDescrizione($this->getRequestParameter('descrizione'));

    $modo_pagamento->save();

    return $this->redirect('modipagamento/list');
  }

  public function executeDelete ()
  {
    $modo_pagamento = ModoPagamentoPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($modo_pagamento);

    $modo_pagamento->delete();

    return $this->redirect('modipagamento/list');
  }
  
  public function handleErrorUpdate()
  {
  	if(!$this->getRequestParameter('id',0))
  		$this->forward('modipagamento','create');
  	else
    	$this->forward('modipagamento','edit');
  }
  
  public function executeDo(){
  	ModoPagamentoPeer::inserisciDefault();
  	$this->forward('modipagamento','list');
  }
}
