<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:09:09
?>

<h2><?php if($tassa->isNew()):?>Nuova Tassa<?php else:?>Modifica Tassa<?php endif?></h2>

<?php use_helper('Object') ?>

<?php echo form_tag('tassa/update') ?>

<?php echo object_input_hidden_tag($tassa, 'getId') ?>

<?php if ($sf_request->hasErrors()): ?>
<div class="validate-error">
  <p>I dati inseriri non sono corretti.
  Correggi i seguenti errori e salva i dati di nuovo:</p>
</div>
<?php endif ?>

<fieldset>
<legend>Dati Tassa</legend>

<table class="banca">
<tbody>
<tr>
  <th>Nome*:</th>
  <td><?php echo object_input_tag($tassa, 'getNome', array (
  'size' => 40,
)) ?></td>
<?php if($sf_request->hasError('nome')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('nome')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Valore*:</th>
  <td><?php echo object_input_tag($tassa, 'getValore', array (
  'size' => 10,
)) ?>%</td>
<?php if($sf_request->hasError('valore')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('valore')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Descrizione:</th>
  <td><?php echo object_input_tag($tassa, 'getDescrizione', array (
  'size' => 40,
)) ?></td>
</tr>
<tr><td colspan="2" align="right"><?php echo submit_tag('Salva') ?></td></tr>
</tbody>
</table>
</fieldset>

</form>
