<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:09:09
?>
<h2>Tasse</h2>

<?php if(count($tassas) > 0):?>
<table class="fatture">
<thead>
<tr>
  <th>Nome</th>
  <th></th>
</tr>
</thead>
<tbody>
<?php foreach ($tassas as $tassa): ?>
<tr>
    <td><?php echo link_to($tassa->getNome(), 'tassa/edit?id='.$tassa->getId()) ?></td>
      <td><?php echo link_to(image_tag('icons_tango/trash-full.png'), 'tassa/delete?id='.$tassa->getId(), 'post=true&confirm=Are you sure?') ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php else:?>
<p>Nessuna tassa disponibile, <?php echo link_to('crea la tua tassa','tassa/create')?>.</p>
<?php endif?>


