<?php
// auto-generated by sfPropelCrud
// date: 11/20/2005 19:10:32
?>
<?php use_helper('Object') ?>

<h2><?php echo $cliente->isNew()?'Modifica Cliente':'Nuovo Cliente'?></h2>

<div id="edit-options">

<?php echo form_tag('cliente/update') ?>

<?php echo object_input_hidden_tag($cliente, 'getId') ?>

<?php if ($sf_request->hasErrors()): ?>
<div class="validate-error">
  <p>I dati inseriti non sono corretti.
  Correggi i seguenti errori e salva i dati di nuovo:</p>
</div>
<?php endif ?>

<ul>
<li id="li-anagrafica" class="selected">
<?php echo ($sf_request->hasError('ragione_sociale') || $sf_request->hasError('piva')?image_tag('icons/icon_alert.gif',array('align'=>'top')).'&nbsp;':'')?>
<?php echo link_to_function('Anagrafica Cliente',							
							visual_effect('fade','fattura',array('duration'=> 0))
							.visual_effect('appear','anagrafica',array('duration'=> 0))
							."Element.addClassName('li-anagrafica','selected');"
							."Element.removeClassName('li-fattura','selected');"
							)?></li>

<li id="li-fattura">
<?php echo ($sf_request->hasError('banca') || $sf_request->hasError('tema_fattura')?image_tag('icons/icon_alert.gif',array('align'=>'top')).'&nbsp;':'')?>
<?php echo link_to_function('Opzioni Fattura',							
							visual_effect('fade','anagrafica',array('duration'=> 0))
							.visual_effect('appear','fattura',array('duration'=> 0))
							."Element.addClassName('li-fattura','selected');"
							."Element.removeClassName('li-anagrafica','selected');"
							)?>
</li>
</ul>


<div class="fieldset tema-fattura <?php echo $sf_request->hasErrors()?'tema-validate-error':''?>" id="anagrafica">
<table class="cliente">
<tbody>
<?php if(UtentePeer::getImpostazione()->getBoolCodiceCliente()):?>
<tr>
  <th>Codice cliente:</th>
  <td><?php echo object_input_tag($cliente, 'getCod', array('size' => 30)) ?></td>
</tr>
<?php endif?>
<tr>
  <th>Azienda:</th>
  <td>
  <?php echo radiobutton_tag('azienda','n',$cliente->getAzienda()=='n'?true:false)?> No
  <?php echo radiobutton_tag('azienda','s',$cliente->getAzienda()=='s'?true:false)?> Si
  </td>
</tr>
<tr>
  <th>Ragione sociale:</th>
  <td>
  <?php echo object_input_tag($cliente, 'getRagioneSociale', array('size' => 60)) ?></td>
  <?php if($sf_request->hasError('ragione_sociale')):?>
<td rowspan="3" class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('ragione_sociale')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Nome:</th>
  <td>
  <?php echo object_input_tag($cliente, 'getNome', array('size' => 50)) ?></td>
</tr>
<tr>
  <th>Cognome:</th>
  <td>
  <?php echo object_input_tag($cliente, 'getCognome', array('size' => 50)) ?></td>
</tr>
<tr>
  <th>Indirizzo:</th>
  <td>
  <?php echo object_input_tag($cliente, 'getVia', array('size' => 60)) ?></td>
</tr>
<tr>
  <th>Citt&agrave;:</th>
  <td>
  <?php echo object_input_tag($cliente, 'getCitta', array('size' => 60)) ?></td>
</tr>
<tr>
  <th>Provincia:</th>
  <td>
  <?php echo object_input_tag($cliente, 'getProvincia', array('size' => 2, 'maxlength' => 2)) ?></td>
</tr>
<tr>
  <th>Cap:</th>
  <td><?php echo object_input_tag($cliente, 'getCap', array('size' => 5, 'maxlength' => 5)) ?></td>
</tr>
<tr>
  <th>P.Iva:</th>
  <td><?php echo object_input_tag($cliente, 'getPiva', array('size' => 20)) ?></td>
  <?php if($sf_request->hasError('piva')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('piva')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>C.F.:</th>
  <td><?php echo object_input_tag($cliente, 'getCf', array('size' => 20)) ?></td>
</tr>
<tr>
  <th>Telefono:</th>
  <td><?php echo object_input_tag($cliente, 'getTelefono', array('size' => 20)) ?></td>
</tr>
<tr>
  <th>Fax:</th>
  <td><?php echo object_input_tag($cliente, 'getFax', array('size' => 20)) ?></td>
</tr>
<tr>
  <th>Cellulare:</th>
  <td><?php echo object_input_tag($cliente, 'getCellulare', array('size' => 20)) ?></td>
</tr>
<tr>
  <th>Email:</th>
  <td><?php echo object_input_tag($cliente, 'getEmail', array('size' => 60)) ?></td>
</tr>
<tr>
<td colspan="2" align="right"><?php echo submit_tag('Salva')?></td>
</tr>
</tbody>
</table>
</div>


<div class="fieldset tema-fattura <?php echo $sf_request->hasErrors()?'tema-validate-error':''?>" id="fattura" style="display: none">
<table class="cliente">
<tbody>
<tr>
  <th>Modo pagamento:</th>
  <td><?php echo object_select_tag($cliente, 'getModoPagamentoId', array('related_class' => 'ModoPagamento')) ?></td>
</tr>
<tr>
  <th>Calcola Ritenuta:</th>
  <td><?php echo select_tag('calcola_ritenuta',options_for_select(Array('a' => 'Auto', 's' => 'Si', 'n' => 'No'), $cliente->getCalcolaRitenutaAcconto()))?></td>
</tr>
<tr>
  <th>Calcola tasse:</th>
  <td><?php echo select_tag('calcola_tasse',options_for_select(array('s'=>'Si','n'=>'No'),$cliente->getCalcolaTasse()))?></td>
</tr>
<tr>
  <th>Scorpora tasse:</th>
  <td><?php echo select_tag('includi_tasse',options_for_select(array('s'=>'Si','n'=>'No'),$cliente->getIncludiTasse()))?></td>
</tr>
<tr>
<th>Banca:</th>
<td><?php echo object_select_tag($cliente, 'getIdBanca', array('related_class' => 'Banca')) ?></td>
<?php if($sf_request->hasError('id_banca')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('id_banca')?>
</td>
<?php endif?>
</tr>
<tr>
<th>Tema Fattura:</th>
<td><?php echo object_select_tag($cliente, 'getIdTemaFattura', array('related_class' => 'TemaFattura')) ?></td>
<?php if($sf_request->hasError('id_tema_fattura')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('id_tema_fattura')?>
</td>
<?php endif?>
</tr>
<tr>
  <th>Note:</th>
  <td><?php echo object_textarea_tag($cliente, 'getNote',array('cols' => '50', 'rows' => '5')) ?></td>
</tr>
<tr>
<td colspan="2" align="right"><?php echo submit_tag('Salva')?></td>
</tr>
</tbody>
</table>

<?php echo input_hidden_tag('stato',$cliente->getStato())?>

</div>

</form>
</div>
