<?php
// auto-generated by sfPropelCrud
// date: 11/20/2005 19:10:32
?>
<?php use_helper('Javascript');?>

<h2>Lista Clienti</h2>

<div id="search" class="search">
<?php echo form_remote_tag(array('url' => 'cliente/search',
								 'update' => 'lista_clienti',
								 'loading' => "Element.show('indicator')",
								 'complete' => "Element.hide('indicator');".visual_effect('highlight', 'lista')))?>
								 
<p><label for="string_search"><strong>Cerca Cliente:</strong></label>
<?php echo input_tag('string_search',isset($string_search)?$string_search:'','size=10')?>&nbsp;<?php echo submit_tag('Cerca')?></p>
</form>
</div>
<div id="indicator" style="display: none;"></div>

<div id="lista_clienti">
<?php 
$array = array('pager'=>$pager);
if(isset($string_search))
	$array['string_search'] = $string_search;
?>
<?php echo include_partial('cliente/lista_clienti',$array);?>
</div>
