<?php
// auto-generated by sfPropelCrud
// date: 11/20/2005 19:10:32
?>
<?php use_helper('Javascript');?>


<!--h2 id="title-menu"> 
<?php echo link_to_function($cliente->toString(),visual_effect('fade','title-menu',array('duration'=>0)).visual_effect('appear','menu',array('duration'=>0.5)),array('title'=>'Getisci Cliente')); ?>
</h2-->

<div id="menu">
<ul>
<li><h2><?php echo $cliente->toString() ?></h2></li>
<li><?php echo link_to(image_tag('icons_tango/new.png',array('alt'=>'Nuova Fattura')),'fattura/create?id_cliente='.$cliente->getID(),array('title'=>'Nuova Fattura'))?></li>
<li><?php echo link_to(image_tag('icons_tango/edit.png',array('alt'=>'Modifica Cliente')),'cliente/edit?id='.$cliente->getID(),array('title'=>'Modifica Cliente'))?></li>
<li><?php echo link_to(image_tag('icons_tango/trash-full.png',array('alt'=>'Elimina Cliente')),'cliente/delete?id='.$cliente->getID(),array('title'=>'Elimina cliente','confirm' => 'Vuoi veramente eliminare il cliente '.$cliente->toString().'?\n(Verranno eliminate anche le fatture associate)'))?></li>
</ul>
</div>

<div class="clear"></div>

<?php include_partial('cliente/contatti',array('cliente'=>$cliente));?>


<div id="tabscheda">
<ul>
<li id="anag" class="select"><?php echo link_to_remote('Anagrafica', array('url' => 'cliente/anagrafica?id='.$cliente->getID(),
									 				'update' => 'scheda_cliente',
									 			    'loading' => "Element.show('indicator')",
									 				'complete' => "Element.removeClassName('list_fat', 'select');Element.removeClassName('opt', 'select');Element.addClassName('anag', 'select');Element.hide('indicator');")) ?></li>
<li id="opt"><?php echo link_to_remote('Opzioni Fattura', array('url' => 'cliente/opzioni?id='.$cliente->getID(),
									 				'update' => 'scheda_cliente',
									 			    'loading' => "Element.show('indicator')",
									 				'complete' => "Element.removeClassName('list_fat', 'select');Element.removeClassName('anag', 'select');Element.addClassName('opt', 'select');Element.hide('indicator');")) ?></li>
<li id="list_fat"><?php echo link_to_remote('Lista Fatture',array('url' => 'fattura/listFilter?cliente_id='.$cliente->getID(),
													'update' => 'scheda_cliente',
													'loading' => "Element.show('indicator')",
													'complete' => "Element.addClassName('list_fat', 'select');Element.removeClassName('opt', 'select');Element.removeClassName('anag', 'select');Element.hide('indicator');"))?></li>
</ul>
</div>


<div id="scheda_cliente">
<?php include_partial('cliente/anagrafica',array('cliente'=>$cliente)) ?>
</div>