<?php
// auto-generated by sfPropelCrud
// date: 2006/09/24 16:12:14
?>
<?php

/**
 * codiciiva actions.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage codiciiva
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 1415 2006-06-11 08:33:51Z fabien $
 */
class codiciivaActions extends sfActions
{
  public function executeIndex ()
  {
    return $this->forward('codiciiva', 'list');
  }

  public function executeList ()
  {
    $this->codice_ivas = CodiceIvaPeer::doSelect(new Criteria());
  }


  public function executeCreate ()
  {
    $this->codice_iva = new CodiceIva();

    $this->setTemplate('edit');
  }

  public function executeEdit ()
  {
    $this->codice_iva = CodiceIvaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->codice_iva);
  }

  public function executeUpdate ()
  {
    if (!$this->getRequestParameter('id', 0))
    {
      $codice_iva = new CodiceIva();
    }
    else
    {
      $codice_iva = CodiceIvaPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($codice_iva);
    }

    $codice_iva->setId($this->getRequestParameter('id'));
    $codice_iva->setIdUtente($this->getUser()->getAttribute('id_utente'));
    $codice_iva->setNome($this->getRequestParameter('nome'));
    $codice_iva->setValore($this->getRequestParameter('valore'));
    $codice_iva->setDescrizione($this->getRequestParameter('descrizione'));

    $codice_iva->save();

    return $this->redirect('codiciiva/list');
  }

  public function executeDelete ()
  {
    $codice_iva = CodiceIvaPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($codice_iva);

    $codice_iva->delete();

    return $this->redirect('codiciiva/list');
  }
  
  public function executeDo(){
  	CodiceIvaPeer::inserisciDefault();
  	return $this->forward('codiciiva','list');
  }
  
  public function handleErrorUpdate()
  {
  	if(!$this->getRequestParameter('id',0))
  		$this->forward('codiciiva','create');
  	else
    	$this->forward('codiciiva','edit');
  }
}
