<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:08:07
?>

<div class="title">
  <h2><?php echo __('Impostazioni')?>
  <?php if($sf_request->hasParameter('success')):?>
    <span class="notice">- <?php echo $sf_request->getParameter('success')?></span>
  <?php endif?>
  </h2>
</div>

<form action="<?php echo url_for('impostazione/edit')?>" method="post">
  <table class="edit" width="100%">
    <?php echo $form; ?>
    <tr>
      <td colspan="2" align="right"><?php echo submit_tag('Salva')?></td>
    </tr>
  </table>
</form>

<?php slot('sidebar')?><?php include_partial('impostazione/sidebar')?><?php end_slot()?>
