<?php
// auto-generated by sfPropelCrud
// date: 2006/09/21 09:37:09
?>
<?php

/**
 * sito actions.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage sito
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 1415 2006-06-11 08:33:51Z fabien $
 */
class sitoActions extends sfActions
{
  
  public function executeIndex ()
  {
  	$this->getRequest()->setParameter('id',6);
    return $this->forward('sito', 'show');
  }

  public function handleErrorInviaContatti()
  {
      $this->forward('sito', 'contatti');
  }

  public function executeShow ()
  {
    $this->pagina = PaginaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->pagina);
  }

  public function executePermalink()
  {
  	$posts = PaginaPeer::doSelect(new Criteria());
  	$title = $this->getRequestParameter('titolo');
  	foreach ($posts as $post)
  	{
  		if ($post->getStrippedTitle() == $title)
  		{
  			break;
  		}
  	}
  	$this->forward404Unless($post);

  	$this->getRequest()->setParameter('id', $post->getId());

  	$this->forward('sito', 'show');
  }
  
  public function executeRegister(){
  	$this->forward('utente','create');
  }

  public function executeContatti(){
  	
  }

  public function executeInviaContatti(){
  	$mail = new sfMail();
        $mail->initialize();
	$mail->setMailer('sendmail');
	$mail->setCharset('utf-8');

	// definition of the required parameters
	$mail->setSender(sfConfig::get('app_admin_from'), sfConfig::get('app_admin_label'));
	$mail->setFrom(sfConfig::get('app_admin_from'), sfConfig::get('app_admin_label'));

	$mail->addAddress(sfConfig::get('app_admin_email'));
	$mail->setSubject('[PIM On-Line] - Nuovo Messaggio');
	$mail->setBody('Ciao Administrator,
è arrivato un nuovo messaggio

Nome: '.$this->getRequestParameter('nome').'
E-Mail: '.$this->getRequestParameter('email').'
Oggetto: '.$this->getRequestParameter('oggetto').'
Messaggio: '.$this->getRequestParameter('messaggio').'

Lo Staff di PIM On-Line
--
AutoMailer PIM On-Line Invitation Code Request');

	// send the email
	$mail->send();
	
  	$this->getRequest()->setParameter('success',1);
  	$this->forward('sito','contatti');
  }
}
