<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:09:56
?>

<div class="title">
  <h2><?php if($form->isNew()):?><?php echo __('Nuovo Tema')?><?php else:?><?php echo __('Modifica Tema')?><?php endif?>
</div>


<?php if($sf_request->hasParameter('success')):?>
  <span style="color:red;font-size: 70%;">- <?php echo __('Tema aggiornato con successo')?></span>
<?php endif?>

</h2>

<form action="<?php echo url_for('temafattura/edit')?>" method="post" enctype="multipart/form-data">
  <table class="edit" width="100%">
    <?php echo $form; ?>
    <tr>
      <td colspan="2" align="right"><?php echo submit_tag('Salva')?></td>
    </tr>
  </table>
</form>

<?php
  slot('sidebar');
    include_partial('temafattura/sidebar');
  end_slot();
?>
