<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:09:56
?>

<div class="title">
  <h2><?php if($tema_fattura->isNew()):?><?php echo __('Nuovo Tema')?><?php else:?><?php echo __('Modifica Tema')?><?php endif?>
</div>


<?php if($sf_request->hasParameter('success')):?>
  <span style="color:red;font-size: 70%;">- <?php echo __('Tema aggiornato con successo')?></span>
<?php endif?>

</h2>
<div id="edit-options">
<?php use_helper('Object') ?>

<?php echo form_tag('temafattura/update', 'multipart=true') ?>

<?php echo object_input_hidden_tag($tema_fattura, 'getId') ?>

<?php if ($sf_request->hasErrors()): ?>
<div class="validate-error">
  <p>I dati inseriri non sono corretti.
  Correggi i seguenti errori e salva i dati di nuovo:</p>
</div>
<?php endif ?>

<div class="title">
  <h3><?php echo __('Nome Tema') ?></h3>
</div>

<div class="fieldset tema-fattura <?php echo $sf_request->hasErrors()?'tema-validate-error':''?>" id="nome">

<table class="banca">
<tr>
<th>Nome*:</th>
<td><?php echo object_input_tag($tema_fattura,'getNome')?>
</td>
<?php if($sf_request->hasError('nome')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('nome')?>
</td>
<?php endif?>
</tr>
<tr>
<th>Logo Ditta:</th>
<td>

<?php if($tema_fattura->getLogo()):?>
<table style="margin-bottom: 5px;margin-top: 5px;">
<tr>
<td>
<?php echo image_tag('/'.sfConfig::get('sf_upload_dir_name').'/thumbnail/'.$tema_fattura->getLogo()) ?>

</td>
</tr>
</table>
<?php endif?>

<?php echo input_file_tag('logo') ?>

</td>
<?php if($sf_request->hasError('logo')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('logo')?>
</td>
<?php endif?>
</tr>
<tr>
<td align="right" colspan="2"><?php echo submit_tag('Salva')?></td>
</tr>
</table>

</div>

<div class="title">
  <h3><?php echo __('Modello Fattura') ?></h3>
</div>

<div class="fieldset tema-fattura <?php echo $sf_request->hasErrors()?'tema-validate-error':''?>" id="theme_header">

<table class="banca">
<tr>
  <th>Modello Fattura*:</th>
  <td><?php echo object_textarea_tag($tema_fattura, 'getTemplate',array('rich'=>false,'size'=>'80x27')
) ?></td>
<?php if($sf_request->hasError('template')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('template')?>
</td>
<?php endif?>
</tr>
<tr>
<td align="right" colspan="2"><?php echo submit_tag('Salva')?></td>
</tr>
</table>

</div>

<div class="title">
  <h3><?php echo __('Stile Fattura') ?></h3>
</div>

<div class="fieldset tema-fattura <?php echo $sf_request->hasErrors()?'tema-validate-error':''?>" id="css">

<table class="banca">
<tr>
  <th>Stile Fattura*:</th>
  <td><?php echo object_textarea_tag($tema_fattura, 'getCss', array (
  'size' => '80x27',
)) ?></td>
<?php if($sf_request->hasError('css')):?>
<td class="validate-error">
<?php echo image_tag('icons/icon_alert.gif')?>&nbsp;<?php echo $sf_request->getError('css')?>
</td>
<?php endif?>
</tr>
<tr>
<td align="right" colspan="2"><?php echo submit_tag('Salva')?></td>
</tr>
</table>

</div>

</form>

</div>

<?php
  slot('sidebar');
    include_partial('temafattura/sidebar');
  end_slot();
?>