<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:09:56
?>

<div class="title">
  <h2><?php echo __('temi fattura')?></h2>
</div>

<?php if(count($tema_fatturas) > 0):?>
  <table width="100%">
  <thead>
  <tr>
    <th>Nome</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <?php foreach ($tema_fatturas as $tema_fattura): ?>
  <tr>
      <td><?php echo link_to($tema_fattura->getNome(), 'temafattura/edit?id='.$tema_fattura->getId()) ?></td>
      <td class="trash"><?php echo link_to(image_tag('icons_tango/trash-full.png', array('alt' => 'delete')), 'temafattura/delete?id='.$tema_fattura->getId(), 'post=true&confirm=Vuoi eliminiare questo tema?') ?></td>
    </tr>
  <?php endforeach; ?>
  </tbody>
  </table>
<?php else:?>
  <p>Nessun tema disponibile, <?php echo link_to('crea il tuo tema fattura','temafattura/create')?>.</p>
<?php endif?>

<?php
  slot('sidebar');
    include_partial('temafattura/sidebar');
  end_slot();
?>