<?php
// auto-generated by sfPropelCrud
// date: 2006/08/16 01:09:56
?>

<div class="title">
  <h2><?php echo __('temi fattura')?></h2>
</div>

<?php if(count($tema_fatturas) > 0):?>
<h2><?php echo __('Lista dei temi'); ?></h2>
  <ul id="lista_temi">
  <?php foreach ($tema_fatturas as $tema_fattura): ?>
      <li><?php echo link_to($tema_fattura->getNome(), 'temafattura/edit?id='.$tema_fattura->getId()) ?>
      <span class="trash"><?php echo link_to(image_tag('icons_tango/trash-full.png', array('alt' => 'delete')), 'temafattura/delete?id='.$tema_fattura->getId(), 'post=true&confirm=Vuoi eliminiare questo tema?') ?></span>
      </li>
  <?php endforeach; ?>
  </ul>
<?php else:?>
<p><?php echo __('Nessun tema disponibile, <a href="%url%">crea il tuo tema fattura</a>', array( '%url%' => url_for('temafattura/create'))); ?>.</p>
<?php endif?>

<?php
  slot('sidebar');
    include_partial('temafattura/sidebar');
  end_slot();
?>