<?php
// auto-generated by sfPropelCrud
// date: 2006/09/21 09:37:09
?>

<table width="100%">
<tr>
<td width="75%" valign="top">
<?php if($pagina->getId() != 6):?>
<h2><?php echo $pagina->getTitolo() ?></h2>
<?php endif?>
<div class="pagina">
<?php echo $pagina->getCorpo() ?>
</div>
</td>
<td valign="top" width="25%">
<?php include_component('login','login',array('adv'=>true));?>
</td>
</tr>
</table>